// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401192512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Admin__89472E95E685A1FC");

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Admin__1A4FA5B90A300820")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Affectation", b =>
                {
                    b.Property<int>("IdAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_affectation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectation"));

                    b.Property<DateTime?>("DateAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_affectation")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdEnseignant")
                        .HasColumnType("int")
                        .HasColumnName("id_enseignant");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("int")
                        .HasColumnName("id_groupe");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    b.HasKey("IdAffectation")
                        .HasName("PK__Affectat__B0B9D1EED2DE9465");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdRole");

                    b.ToTable("Affectation", (string)null);
                });

            modelBuilder.Entity("Infrastructure.ConfigurationIum", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_config");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<DateTime?>("DateConfiguration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_configuration")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("GenerationCodeAutorisee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("generation_code_autorisee");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    b.Property<string>("PeriodeQuota")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("periode_quota");

                    b.Property<int?>("QuotaRequetes")
                        .HasColumnType("int")
                        .HasColumnName("quota_requetes");

                    b.Property<int?>("QuotaTokens")
                        .HasColumnType("int")
                        .HasColumnName("quota_tokens");

                    b.HasKey("IdConfig")
                        .HasName("PK__Configur__8F0A1FB2901856BE");

                    b.HasIndex(new[] { "IdProjet" }, "UQ__Configur__36C5661C00B13D51")
                        .IsUnique();

                    b.ToTable("Configuration_IA", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Contribution", b =>
                {
                    b.Property<int>("IdContribution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contribution");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContribution"));

                    b.Property<DateTime?>("DateCommit")
                        .HasColumnType("datetime")
                        .HasColumnName("date_commit");

                    b.Property<string>("HashCommit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hash_commit");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    b.Property<int?>("LignesAjoutees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("lignes_ajoutees");

                    b.Property<int?>("LignesSupprimees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("lignes_supprimees");

                    b.Property<string>("MessageCommit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message_commit");

                    b.HasKey("IdContribution")
                        .HasName("PK__Contribu__95E7F2CE51D9ADB7");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdProjet");

                    b.HasIndex(new[] { "HashCommit" }, "UQ__Contribu__6557D4D019C39649")
                        .IsUnique()
                        .HasFilter("[hash_commit] IS NOT NULL");

                    b.ToTable("Contribution", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_enseignant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("Departement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("departement");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Specialite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("specialite");

                    b.HasKey("IdEnseignant")
                        .HasName("PK__Enseigna__CFF6D48646A0763C");

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Enseigna__1A4FA5B9CC09AB17")
                        .IsUnique();

                    b.ToTable("Enseignant", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Etudiant", b =>
                {
                    b.Property<int>("IdEtudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtudiant"));

                    b.Property<string>("CodeApogee")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code_apogee");

                    b.Property<string>("Filiere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("filiere");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Niveau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("niveau");

                    b.HasKey("IdEtudiant")
                        .HasName("PK__Etudiant__D1104AC72D94C259");

                    b.HasIndex(new[] { "CodeApogee" }, "UQ__Etudiant__16C4CFE1D5FE85EE")
                        .IsUnique();

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Etudiant__1A4FA5B9ABBF6F4D")
                        .IsUnique();

                    b.ToTable("Etudiant", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Evaluation", b =>
                {
                    b.Property<int>("IdEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evaluation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluation"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime?>("DateEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_evaluation")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int")
                        .HasColumnName("id_enseignant");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    b.Property<decimal?>("IndicateurDependanceIa")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("indicateur_dependance_ia");

                    b.Property<decimal?>("Note")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("note");

                    b.HasKey("IdEvaluation")
                        .HasName("PK__Evaluati__0B77AA116C9AE613");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdProjet");

                    b.ToTable("Evaluation", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Groupe", b =>
                {
                    b.Property<int>("IdGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_groupe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupe"));

                    b.Property<int>("IdProjet")
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nom_groupe");

                    b.HasKey("IdGroupe")
                        .HasName("PK__Groupe__6E0AF8301A830A66");

                    b.HasIndex("IdProjet");

                    b.ToTable("Groupe", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Projet", b =>
                {
                    b.Property<int>("IdProjet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjet"));

                    b.Property<DateOnly?>("DateDebut")
                        .HasColumnType("date")
                        .HasColumnName("date_debut");

                    b.Property<DateOnly?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("date_fin");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Duree")
                        .HasColumnType("int")
                        .HasColumnName("duree");

                    b.Property<int?>("IdEnseignant")
                        .HasColumnType("int")
                        .HasColumnName("id_enseignant");

                    b.Property<string>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("En cours")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titre");

                    b.Property<string>("UrlGit")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url_git");

                    b.HasKey("IdProjet")
                        .HasName("PK__Projet__36C5661D2CDF80AB");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("Projet", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Prompt", b =>
                {
                    b.Property<int>("IdPrompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_prompt");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrompt"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<DateTime?>("DatePrompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_prompt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int")
                        .HasColumnName("id_projet");

                    b.Property<int?>("NbTokensEntree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("nb_tokens_entree");

                    b.Property<int?>("NbTokensSortie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("nb_tokens_sortie");

                    b.HasKey("IdPrompt")
                        .HasName("PK__Prompt__368514A85D7E4526");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdProjet");

                    b.ToTable("Prompt", (string)null);
                });

            modelBuilder.Entity("Infrastructure.ReponseIum", b =>
                {
                    b.Property<int>("IdReponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reponse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReponse"));

                    b.Property<string>("ContenuReponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu_reponse");

                    b.Property<DateTime?>("DateReponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_reponse")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPrompt")
                        .HasColumnType("int")
                        .HasColumnName("id_prompt");

                    b.Property<string>("ModeleIa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modele_ia");

                    b.HasKey("IdReponse")
                        .HasName("PK__Reponse___861C0C2C2684B7FC");

                    b.HasIndex("IdPrompt");

                    b.ToTable("Reponse_IA", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole")
                        .HasName("PK__Role__3D48441D528017A9");

                    b.HasIndex(new[] { "NomRole" }, "UQ__Role__95A62FB223DCB138")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Actif")
                        .HasColumnName("statut");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Utilisat__1A4FA5B8AEDF0317");

                    b.HasIndex(new[] { "Email" }, "UQ__Utilisat__AB6E6164AF503755")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Admin", b =>
                {
                    b.HasOne("Infrastructure.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Infrastructure.Admin", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__id_utilis__6383C8BA");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Infrastructure.Affectation", b =>
                {
                    b.HasOne("Infrastructure.Enseignant", "IdEnseignantNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdEnseignant")
                        .HasConstraintName("FK__Affectati__id_en__7C4F7684");

                    b.HasOne("Infrastructure.Etudiant", "IdEtudiantNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdEtudiant")
                        .IsRequired()
                        .HasConstraintName("FK__Affectati__id_et__797309D9");

                    b.HasOne("Infrastructure.Groupe", "IdGroupeNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdGroupe")
                        .IsRequired()
                        .HasConstraintName("FK__Affectati__id_gr__7A672E12");

                    b.HasOne("Infrastructure.Role", "IdRoleNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK__Affectati__id_ro__7B5B524B");

                    b.Navigation("IdEnseignantNavigation");

                    b.Navigation("IdEtudiantNavigation");

                    b.Navigation("IdGroupeNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("Infrastructure.ConfigurationIum", b =>
                {
                    b.HasOne("Infrastructure.Projet", "IdProjetNavigation")
                        .WithOne("ConfigurationIum")
                        .HasForeignKey("Infrastructure.ConfigurationIum", "IdProjet")
                        .IsRequired()
                        .HasConstraintName("FK__Configura__id_pr__18EBB532");

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Infrastructure.Contribution", b =>
                {
                    b.HasOne("Infrastructure.Etudiant", "IdEtudiantNavigation")
                        .WithMany("Contributions")
                        .HasForeignKey("IdEtudiant")
                        .IsRequired()
                        .HasConstraintName("FK__Contribut__id_et__02084FDA");

                    b.HasOne("Infrastructure.Projet", "IdProjetNavigation")
                        .WithMany("Contributions")
                        .HasForeignKey("IdProjet")
                        .IsRequired()
                        .HasConstraintName("FK__Contribut__id_pr__02FC7413");

                    b.Navigation("IdEtudiantNavigation");

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Infrastructure.Enseignant", b =>
                {
                    b.HasOne("Infrastructure.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Enseignant")
                        .HasForeignKey("Infrastructure.Enseignant", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Enseignan__id_ut__6754599E");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Infrastructure.Etudiant", b =>
                {
                    b.HasOne("Infrastructure.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Etudiant")
                        .HasForeignKey("Infrastructure.Etudiant", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Etudiant__id_uti__6C190EBB");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Infrastructure.Evaluation", b =>
                {
                    b.HasOne("Infrastructure.Enseignant", "IdEnseignantNavigation")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdEnseignant")
                        .IsRequired()
                        .HasConstraintName("FK__Evaluatio__id_en__1332DBDC");

                    b.HasOne("Infrastructure.Etudiant", "IdEtudiantNavigation")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdEtudiant")
                        .IsRequired()
                        .HasConstraintName("FK__Evaluatio__id_et__114A936A");

                    b.HasOne("Infrastructure.Projet", "IdProjetNavigation")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdProjet")
                        .IsRequired()
                        .HasConstraintName("FK__Evaluatio__id_pr__123EB7A3");

                    b.Navigation("IdEnseignantNavigation");

                    b.Navigation("IdEtudiantNavigation");

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Infrastructure.Groupe", b =>
                {
                    b.HasOne("Infrastructure.Projet", "IdProjetNavigation")
                        .WithMany("Groupes")
                        .HasForeignKey("IdProjet")
                        .IsRequired()
                        .HasConstraintName("FK__Groupe__id_proje__72C60C4A");

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Infrastructure.Projet", b =>
                {
                    b.HasOne("Infrastructure.Enseignant", "IdEnseignantNavigation")
                        .WithMany("Projets")
                        .HasForeignKey("IdEnseignant")
                        .HasConstraintName("FK__Projet__id_ensei__6FE99F9F");

                    b.Navigation("IdEnseignantNavigation");
                });

            modelBuilder.Entity("Infrastructure.Prompt", b =>
                {
                    b.HasOne("Infrastructure.Etudiant", "IdEtudiantNavigation")
                        .WithMany("Prompts")
                        .HasForeignKey("IdEtudiant")
                        .IsRequired()
                        .HasConstraintName("FK__Prompt__id_etudi__08B54D69");

                    b.HasOne("Infrastructure.Projet", "IdProjetNavigation")
                        .WithMany("Prompts")
                        .HasForeignKey("IdProjet")
                        .IsRequired()
                        .HasConstraintName("FK__Prompt__id_proje__09A971A2");

                    b.Navigation("IdEtudiantNavigation");

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Infrastructure.ReponseIum", b =>
                {
                    b.HasOne("Infrastructure.Prompt", "IdPromptNavigation")
                        .WithMany("ReponseIa")
                        .HasForeignKey("IdPrompt")
                        .IsRequired()
                        .HasConstraintName("FK__Reponse_I__id_pr__0D7A0286");

                    b.Navigation("IdPromptNavigation");
                });

            modelBuilder.Entity("Infrastructure.Enseignant", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("Evaluations");

                    b.Navigation("Projets");
                });

            modelBuilder.Entity("Infrastructure.Etudiant", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("Contributions");

                    b.Navigation("Evaluations");

                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Infrastructure.Groupe", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Infrastructure.Projet", b =>
                {
                    b.Navigation("ConfigurationIum");

                    b.Navigation("Contributions");

                    b.Navigation("Evaluations");

                    b.Navigation("Groupes");

                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Infrastructure.Prompt", b =>
                {
                    b.Navigation("ReponseIa");
                });

            modelBuilder.Entity("Infrastructure.Role", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Infrastructure.Utilisateur", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Enseignant");

                    b.Navigation("Etudiant");
                });
#pragma warning restore 612, 618
        }
    }
}
