[User_service]
# Replace with the exact static IP you set up in your Virtual Network Editor
192.168.139.128 ansible_user=vagrant ansible_password=vagrant ansible_ssh_common_args='-o StrictHostKeyChecking=no'