// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260510200916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Admin__89472E95E685A1FC");

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Admin__1A4FA5B90A300820")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Affectation", b =>
                {
                    b.Property<int>("IdAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAffectation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectation"));

                    b.Property<DateTime?>("DateAffectation")
                        .HasColumnType("datetime")
                        .HasColumnName("DateAffectation");

                    b.Property<int?>("IdEnseignant")
                        .HasColumnType("int")
                        .HasColumnName("IdEnseignant");

                    b.Property<int?>("IdEtudiant")
                        .HasColumnType("int")
                        .HasColumnName("IdEtudiant");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("int")
                        .HasColumnName("IdGroupe");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("IdRole");

                    b.HasKey("IdAffectation")
                        .HasName("PK_Affectation");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdRole");

                    b.ToTable("Affectation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdClasse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("AnneeAcademique")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AnneeAcademique");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("DateCreation");

                    b.Property<int>("EffectifMax")
                        .HasColumnType("int")
                        .HasColumnName("EffectifMax");

                    b.Property<string>("NomClasse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomClasse");

                    b.HasKey("IdClasse")
                        .HasName("PK_Classe");

                    b.ToTable("Classe", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_enseignant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("Departement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("departement");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Specialite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("specialite");

                    b.HasKey("IdEnseignant")
                        .HasName("PK__Enseigna__CFF6D48646A0763C");

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Enseigna__1A4FA5B9CC09AB17")
                        .IsUnique();

                    b.ToTable("Enseignant", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EnseignantClasse", b =>
                {
                    b.Property<int>("IdEnseignantClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEnseignantClasse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignantClasse"));

                    b.Property<int?>("ClasseIdClasse")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAffectation")
                        .HasColumnType("datetime")
                        .HasColumnName("DateAffectation");

                    b.Property<int?>("EnseignantIdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("IdClasse");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int")
                        .HasColumnName("IdEnseignant");

                    b.HasKey("IdEnseignantClasse");

                    b.HasIndex("ClasseIdClasse");

                    b.HasIndex("EnseignantIdEnseignant");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("EnseignantClasse", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Etudiant", b =>
                {
                    b.Property<int>("IdEtudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etudiant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtudiant"));

                    b.Property<string>("CodeApogee")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code_apogee");

                    b.Property<string>("Filiere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("filiere");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Niveau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("niveau");

                    b.HasKey("IdEtudiant")
                        .HasName("PK__Etudiant__D1104AC72D94C259");

                    b.HasIndex(new[] { "CodeApogee" }, "UQ__Etudiant__16C4CFE1D5FE85EE")
                        .IsUnique();

                    b.HasIndex(new[] { "IdUtilisateur" }, "UQ__Etudiant__1A4FA5B9ABBF6F4D")
                        .IsUnique();

                    b.ToTable("Etudiant", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_role");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom_role");

                    b.HasKey("IdRole")
                        .HasName("PK__Role__3D48441D528017A9");

                    b.HasIndex(new[] { "NomRole" }, "UQ__Role__95A62FB223DCB138")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_creation")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Actif")
                        .HasColumnName("statut");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Utilisat__1A4FA5B8AEDF0317");

                    b.HasIndex(new[] { "Email" }, "UQ__Utilisat__AB6E6164AF503755")
                        .IsUnique();

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.HasOne("Domain.Entities.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Domain.Entities.Admin", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__id_utilis__6383C8BA");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Affectation", b =>
                {
                    b.HasOne("Domain.Entities.Enseignant", "IdEnseignantNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdEnseignant")
                        .HasConstraintName("FK_Affectation_Enseignant");

                    b.HasOne("Domain.Entities.Etudiant", "IdEtudiantNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdEtudiant")
                        .HasConstraintName("FK_Affectation_Etudiant");

                    b.HasOne("Domain.Entities.Role", "IdRoleNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Affectation_Role");

                    b.Navigation("IdEnseignantNavigation");

                    b.Navigation("IdEtudiantNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Enseignant", b =>
                {
                    b.HasOne("Domain.Entities.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Enseignant")
                        .HasForeignKey("Domain.Entities.Enseignant", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Enseignan__id_ut__6754599E");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Domain.Entities.EnseignantClasse", b =>
                {
                    b.HasOne("Domain.Entities.Classe", null)
                        .WithMany("EnseignantClasses")
                        .HasForeignKey("ClasseIdClasse");

                    b.HasOne("Domain.Entities.Enseignant", null)
                        .WithMany("EnseignantClasses")
                        .HasForeignKey("EnseignantIdEnseignant");

                    b.HasOne("Domain.Entities.Classe", "IdClasseNavigation")
                        .WithMany()
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EnseignantClasse_Classe");

                    b.HasOne("Domain.Entities.Enseignant", "IdEnseignantNavigation")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EnseignantClasse_Enseignant");

                    b.Navigation("IdClasseNavigation");

                    b.Navigation("IdEnseignantNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Etudiant", b =>
                {
                    b.HasOne("Domain.Entities.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Etudiant")
                        .HasForeignKey("Domain.Entities.Etudiant", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Etudiant__id_uti__6C190EBB");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Classe", b =>
                {
                    b.Navigation("EnseignantClasses");
                });

            modelBuilder.Entity("Domain.Entities.Enseignant", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("EnseignantClasses");
                });

            modelBuilder.Entity("Domain.Entities.Etudiant", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Enseignant");

                    b.Navigation("Etudiant");
                });
#pragma warning restore 612, 618
        }
    }
}
