// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unprompted.Services.Projet.Infrastructure.Data;

#nullable disable

namespace Unprompted.Services.Projet.Infrastructure.Migrations
{
    [DbContext(typeof(ProjetDbContext))]
    [Migration("20260522172852_InitialCreateMicroserviceProjet")]
    partial class InitialCreateMicroserviceProjet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Affectation", b =>
                {
                    b.Property<int>("IdAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectation"));

                    b.Property<DateTime?>("DateAffectation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("int");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.HasKey("IdAffectation");

                    b.HasIndex("IdEtudiant");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdRole");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.ConfigurationIum", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfig"));

                    b.Property<bool?>("GenerationCodeAutorisee")
                        .HasColumnType("bit");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int");

                    b.Property<string>("PeriodeQuota")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QuotaRequetes")
                        .HasColumnType("int");

                    b.Property<int?>("QuotaTokens")
                        .HasColumnType("int");

                    b.HasKey("IdConfig");

                    b.HasIndex("IdProjet")
                        .IsUnique();

                    b.ToTable("ConfigurationsIum");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Groupe", b =>
                {
                    b.Property<int>("IdGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupe"));

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProjet")
                        .HasColumnType("int");

                    b.Property<string>("NomGroupe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGroupe");

                    b.HasIndex("IdProjet");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Projet", b =>
                {
                    b.Property<int>("IdProjet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjet"));

                    b.Property<string>("CahierDesChargesPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdProjet");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Affectation", b =>
                {
                    b.HasOne("Unprompted.Services.Projet.Domain.Entities.Groupe", "IdGroupeNavigation")
                        .WithMany("Affectations")
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGroupeNavigation");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.ConfigurationIum", b =>
                {
                    b.HasOne("Unprompted.Services.Projet.Domain.Entities.Projet", "IdProjetNavigation")
                        .WithOne("ConfigurationIum")
                        .HasForeignKey("Unprompted.Services.Projet.Domain.Entities.ConfigurationIum", "IdProjet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Groupe", b =>
                {
                    b.HasOne("Unprompted.Services.Projet.Domain.Entities.Projet", "IdProjetNavigation")
                        .WithMany("Groupes")
                        .HasForeignKey("IdProjet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProjetNavigation");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Groupe", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("Unprompted.Services.Projet.Domain.Entities.Projet", b =>
                {
                    b.Navigation("ConfigurationIum");

                    b.Navigation("Groupes");
                });
#pragma warning restore 612, 618
        }
    }
}
