FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Créer le dossier secret de ChromaDB
RUN mkdir -p /root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/

# Copier le fichier que tu as téléchargé manuellement vers ce dossier
COPY onnx.tar.gz /root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
