name: CI — Frontend (avec React)


on:
  push:
    paths:
      - 'Frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    paths:
      - 'Frontend/**'


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install dependencies
        working-directory: Frontend
        run: npm ci

      - name: Lint
        working-directory: Frontend
        run: npm run lint


      - name: Build
        working-directory: Frontend
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://localhost:5000' }}
      - name: Build Docker image
        run: |
          docker build -f Frontend/DOCKERFILE -t unprompted/frontend:${{ github.sha }} Frontend/
          docker tag unprompted/frontend:${{ github.sha }} unprompted/frontend:latest

      - name: Security scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: unprompted/frontend:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: '1'
          ignore-unfixed: true

      - name: Push to registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref =='refs/heads/feature/tests'
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_URL }} \
            -u ${{ secrets.REGISTRY_USER }} --password-stdin
          docker push ${{ secrets.REGISTRY_URL }}/unprompted/frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_URL }}/unprompted/frontend:latest
